name: ScenamaticaTest
version: '${project.version}'
main: net.kunmc.lab.scenamaticatest.ScenamaticaTest
api-version: 1.16
load: STARTUP

commands:
  sc002_3_4:
    description: Perform SC-002, SC-003, SC-004 expected actions.
  sc030:
    description: Perform SC-030 expected actions.
