name: "Scenamatica Scenario Test"

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          cache: "maven"
          distribution: "zulu"
      - name: "Build"
        run: mvn -B package --file pom.xml
      - name: "Run Scenamatica tests"
        uses: teamkun/scenamatica-action@feat/pull-request
        with:
          plugin: target/ScenamaticaTest-1.0.0.jar
